services:

  postgres:
    image: postgres:latest
    restart: no
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-whatsnew}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: whatsnew
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8080:8080"
    restart: no
    depends_on:
      - postgres

volumes:
  postgres_data:
