services:
  postgres:
    image: postgres:latest
    container_name: postgres_WhatsNew
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-whatsnew}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: whatsnew
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
